name: dask-scale
channels:
  - conda-forge
dependencies:
  - python=3.8.*
  - dask
  - bokeh
  - python-graphviz
  - pyarrow
  - rise
  - isort
  - notebook
  - ipywidgets
  - jupyterlab
  - nodejs
  - dask_labextension
  - matplotlib
  - seaborn
