name: scale-df-dev
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8.*
  - dask
  - bokeh
  - python-graphviz
  - pyarrow
  - jupyter_contrib_nbextensions
  - rise
  - isort
  - notebook
  - ipywidgets
# - jupyterlab
#    - xarray
#   - jupyter-server-proxy
#  - dask_labextension
#  - nodejs
