name: scale-df-dev
channels:
  - conda-forge
dependencies:
  - python=3.8.*
  - dask
  - bokeh
  - python-graphviz
  - pyarrow
  - jupyter_contrib_nbextensions
  - rise
  - isort
  - notebook
  - ipywidgets
  - jupyterlab
  - nodejs
  - dask_labextension
#    - xarray
#   - jupyter-server-proxy

